{{- $pvc := .Values.contentStorage.filesystem.pvc -}}
{{- if $pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc.existingClaim }}
  {{- if $pvc.preserveOnDelete }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - {{ $pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $pvc.size }}
  {{- if $pvc.storageClassName }}
  storageClassName: {{ $pvc.storageClassName }}
  {{- end }}
{{- end }}
