name: bd-site

on:
  push:
    branches:
      - 'main'

env:
  NAME: bd-site
  DOCKER_REGISTRY: ghcr.io
  DOCKER_ORG: berryhill
  DOCKER_IMAGE: bd-site
  DOCKER_TAG: 0.0.25
  GITHUB_USER: berryhill
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  LINODE_KUBECONFIG: ${{ secrets.LINODE_KUBECONFIG }}
  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN}}

jobs:
  build-push:
    runs-on: ubuntu-latest
    # outputs:
    #   sha: ${{ steps.sha.outputs.SHA }}
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.GITHUB_USER }}
        password: ${{ env.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build \
          --build-arg DOT_ENV="${{ secrets.DOT_ENV }}" \
          -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
        docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    # environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.LINODE_KUBECONFIG }}" | base64 -d > ~/.kube/config

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy using Helm
      run: |
        helm upgrade --install bd-site ./helm -f ./helm/values.yaml --install --set dopplerToken="${{ env.DOPPLER_TOKEN }}"
